name: QA Automation Pipeline

on:
  push:
    branches: [ main ]

jobs:

  automation-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Playwright
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Run automation tests
        run: mvn clean test